#' Format `openxlsx` worksheet based on changes
#'
#' Highlights cells that changed, coloring differently for increasing, decreasing, and non-numeric cells.
#' Typically used on a worksheet that contains the `$sheet.diff` dataframe from the same sheet comparison as provided
#' in the `cur.sheet` argument. In some cases it may be useful to define custom color schemes (e.g., if increasing numbers are good
#' and decreasing numbers are bad, you may want green and red foregrounds for those types of changes). Individual styles can be provided
#' with optional arguments see `?openxlsx::createStyle` for options in defining styles.
#'
#' In some cases it may make sense to reverse the color scheme of numeric changes for individual rows, columns,
#' or cells (e.g., when scanning fishery model outputs, increasing fish escapement and decreasing fish exploitation rates logically should both show the same color.
#' Similarly, increasing profits and decreasing costs logically should both show the same color.). Optional arguments `rows.invert`, `cols.invert`, and
#' `df.invert` allow you to specify individual regions of the dataframe to reverse the color scheme.
#'
#' @param wb openxlsx workbook to make on which to make changes.
#' @param cur.sheet sheet name in openxlsx workbook on which to make changes.
#' @param sheet.comp list of comparison dataframes generated by `sheet_comp()`
#' @param rows.invert Optional vector of row numbers to invert color scheme for increase vs decrease.
#' @param cols.invert Optional vector of column numbers to invert color scheme for increase vs decrease.
#' @param df.invert Optional data frame with `$row` and `$col` entries to identify individual cells to invert color schemes for increase vs decrease. Defaults to NULL.
#' @param change.color Hex code for color to highlight cells that changed (and were not numerics). Defaults to lavendar ("#E1C0FF").
#' @param pos.color As `change.color`, but for numeric cells that increase in value. Defaults to coral ("#E1C0FF").
#' @param neg.color As `change.color`, but for numeric cells that decrease in value. Defaults to light green ("#C6EFCE")
#'
#' @export
add_changed_formats = function(wb, cur.sheet,
                               sheet.comp, rows.invert = NULL, cols.invert = NULL,
                               df.invert = NULL, ## must have $row and $col arguments
                               change.color = "#E1C0FF",
                               pos.color = "#FFC7CE",
                               neg.color = "#C6EFCE"){

  ## If any inversions are identified, apply them to the increase and decrease
  ## But make sure we're not inverting "no change" to "change". Hence the `& mat.changed` bits.
  sheet.comp.static <- sheet.comp
  if(!is.null(rows.invert)){
    sheet.comp$mat.diff.decrease[rows.invert,] = sheet.comp.static$mat.diff.increase[rows.invert,] &
      sheet.comp$mat.changed[rows.invert,]
    sheet.comp$mat.diff.increase[rows.invert,] = sheet.comp.static$mat.diff.decrease[rows.invert,] &
      sheet.comp$mat.changed[rows.invert,]
  }
  if(!is.null(cols.invert)){
    sheet.comp$mat.diff.decrease[ , cols.invert] = sheet.comp.static$mat.diff.increase[ , cols.invert] &
      sheet.comp$mat.changed[ , cols.invert]
    sheet.comp$mat.diff.increase[ , cols.invert] = sheet.comp.static$mat.diff.decrease[ , cols.invert] &
      sheet.comp$mat.changed[ , cols.invert]
  }
  if(!is.null(df.invert)){
    sheet.comp$mat.diff.decrease[df.invert$row , df.invert$col] =
      sheet.comp.static$mat.diff.increase[df.invert$row , df.invert$col] &
      sheet.comp$mat.changed[df.invert$row , df.invert$col]
    sheet.comp$mat.diff.increase[df.invert$row , df.invert$col] =
      sheet.comp.static$mat.diff.decrease[df.invert$row , df.invert$col]&
      sheet.comp$mat.changed[df.invert$row , df.invert$col]
  }

  ## color text changes
  dims_text = mat_to_a1(sheet.comp$mat.diff.text)
  dims_neg = mat_to_a1(sheet.comp$mat.diff.decrease)
  dims_pos = mat_to_a1(sheet.comp$mat.diff.increase)

  if(!is.null(dims_text)){
    wb <- wb |>
      openxlsx2::wb_add_fill(sheet = cur.sheet,
                  dims = dims_text,
                  color = openxlsx2::wb_color(hex = change.color))
  }
  if(!is.null(dims_neg)){
    wb <- wb |>
      openxlsx2::wb_add_fill(sheet = cur.sheet,
                  dims = dims_neg,
                  color = openxlsx2::wb_color(hex = neg.color))
  }
  if(!is.null(dims_pos)){
    wb <- wb |>
      openxlsx2::wb_add_fill(sheet = cur.sheet,
                dims = dims_pos,
                color = openxlsx2::wb_color(hex = pos.color))
  }
  return(wb)
}
