#' Format `openxlsx2` worksheet based on changes
#'
#' Highlights cells that changed, coloring differently for increasing, decreasing, and non-numeric cells.
#' Typically used on a worksheet that contains the `$sheet.diff` dataframe from the same sheet comparison as provided
#' in the `cur_sheet` argument. In some cases it may be useful to define custom color schemes (e.g., if increasing numbers are good
#' and decreasing numbers are bad, you may want green and red foregrounds for those types of changes). Individual colors can be provided for increasing, decreasing, or text changes.
#' Similarly, increasing profits and decreasing costs logically should both show the same color. Optional arguments `rows_invert`, `cols_invert`, and
#' `df_invert` allow you to specify individual regions of the dataframe to reverse the color scheme.
#'
#' @param wb openxlsx2 workbook to make on which to make changes.
#' @param cur_sheet sheet name in openxlsx2 workbook on which to make changes.
#' @param sheet_comp list of comparison dataframes generated by `sheet_comp()`
#' @param rows_invert Optional vector of row numbers to invert color scheme for increase vs decrease.
#' @param cols_invert Optional vector of column numbers to invert color scheme for increase vs decrease.
#' @param df_invert Optional data frame with `$row` and `$col` entries to identify individual cells to invert color schemes for increase vs decrease. Defaults to NULL.
#' @param change_color Hex code for color to highlight cells that changed (and were not numerics). Defaults to lavendar ("#E1C0FF").
#' @param pos_color As `change_color`, but for numeric cells that increase in value. Defaults to coral ("#E1C0FF").
#' @param neg_color As `change_color`, but for numeric cells that decrease in value. Defaults to light green ("#C6EFCE")
#'
#' @export
add_changed_formats <- function(wb, cur_sheet,
                                sheet_comp, rows_invert = NULL, cols_invert = NULL,
                                df_invert = NULL, ## must have $row and $col arguments
                                change_color = "#E1C0FF",
                                pos_color = "#FFC7CE",
                                neg_color = "#C6EFCE") {
  ## If any inversions are identified, apply them to the increase and decrease
  ## But make sure we're not inverting "no change" to "change". Hence the `& mat_changed` bits.
  sheet_comp_static <- sheet_comp
  if (!is.null(rows_invert)) {
    sheet_comp$mat_diff_decrease[rows_invert, ] <- sheet_comp_static$mat_diff_increase[rows_invert, ] &
      sheet_comp$mat_changed[rows_invert, ]
    sheet_comp$mat_diff_increase[rows_invert, ] <- sheet_comp_static$mat_diff_decrease[rows_invert, ] &
      sheet_comp$mat_changed[rows_invert, ]
  }
  if (!is.null(cols_invert)) {
    sheet_comp$mat_diff_decrease[, cols_invert] <- sheet_comp_static$mat_diff_increase[, cols_invert] &
      sheet_comp$mat_changed[, cols_invert]
    sheet_comp$mat_diff_increase[, cols_invert] <- sheet_comp_static$mat_diff_decrease[, cols_invert] &
      sheet_comp$mat_changed[, cols_invert]
  }
  if (!is.null(df_invert)) {
    sheet_comp$mat_diff_decrease[df_invert$row, df_invert$col] <-
      sheet_comp_static$mat_diff_increase[df_invert$row, df_invert$col] &
        sheet_comp$mat_changed[df_invert$row, df_invert$col]
    sheet_comp$mat_diff_increase[df_invert$row, df_invert$col] <-
      sheet_comp_static$mat_diff_decrease[df_invert$row, df_invert$col] &
        sheet_comp$mat_changed[df_invert$row, df_invert$col]
  }

  ## color text changes
  dims_text <- mat_to_a1(sheet_comp$mat_diff_text)
  dims_neg <- mat_to_a1(sheet_comp$mat_diff_decrease)
  dims_pos <- mat_to_a1(sheet_comp$mat_diff_increase)

  if (!is.null(dims_text)) {
    wb <- wb |>
      openxlsx2::wb_add_fill(
        sheet = cur_sheet,
        dims = dims_text,
        color = openxlsx2::wb_color(hex = change_color)
      )
  }
  if (!is.null(dims_neg)) {
    wb <- wb |>
      openxlsx2::wb_add_fill(
        sheet = cur_sheet,
        dims = dims_neg,
        color = openxlsx2::wb_color(hex = neg_color)
      )
  }
  if (!is.null(dims_pos)) {
    wb <- wb |>
      openxlsx2::wb_add_fill(
        sheet = cur_sheet,
        dims = dims_pos,
        color = openxlsx2::wb_color(hex = pos_color)
      )
  }
  return(wb)
}
