#' Format `openxlsx` worksheet based on changes
#'
#' Highlights cells that changed, coloring differently for increasing, decreasing, and non-numeric cells.
#' Typically used on a worksheet that contains the `$sheet.diff` dataframe from the same sheet comparison as provided
#' in the `cur.sheet` argument. In some cases it may be useful to define custom color schemes (e.g., if increasing numbers are good
#' and decreasing numbers are bad, you may want green and red foregrounds for those types of changes). Individual styles can be provided
#' with optional arguments see `?openxlsx::createStyle` for options in defining styles.
#'
#' In some cases it may make sense to reverse the color scheme of numeric changes for individual rows, columns,
#' or cells (e.g., when scanning fishery model outputs, increasing fish escapement and decreasing fish exploitation rates logically should both show the same color.
#' Similarly, increasing profits and decreasing costs logically should both show the same color.). Optional arguments `rows.invert`, `cols.invert`, and
#' `df.invert` allow you to specify individual regions of the dataframe to reverse the color scheme.
#'
#' @param wb openxlsx workbook to make on which to make changes.
#' @param cur.sheet sheet name in openxlsx workbook on which to make changes.
#' @param sheet.comp list of comparison dataframes generated by `sheet_comp()`
#' @param rows.invert Optional vector of row numbers to invert color scheme for increase vs decrease.
#' @param cols.invert Optional vector of column numbers to invert color scheme for increase vs decrease.
#' @param df.invert Optional data frame with `$row` and `$col` entries to indentify individual cells to invert color schemes for increase vs decrease. Defaults to NULL.
#' @param nofillStyle Optional openxlsx style object for cells with no changes flagged. Default has black text, white foreground. Create custom style with `openxlsx::createStyle()`.
#' @param changeStyle As `nofillStyle`, but for non-numeric cells with changed values. Default has black text, light purple forecround.
#' @param posStyle As `nofillStyle`, but for numeric cells that increase in value. Default has black text, light coral foreground.
#' @param negStyle As `nofillStyle`, but for numeric cells that decrease in value. Default has black text, light green foreground.
#'
#' @export

add_changed_formats = function(wb, cur.sheet,
                               sheet.comp, rows.invert = NULL, cols.invert = NULL,
                               df.invert = NULL, ## must have $row and $col arguments
                               nofillStyle = NULL, ##
                               changeStyle = NULL,
                               posStyle = NULL,
                               negStyle = NULL){
  if(!is.null(nofillStyle) & !methods::is(nofillStyle, "Style")){
    cli::cli_abort("`nofillStyle` must be NULL or an openxlsx style created with `createStyle()`.")
  }
  if(!is.null(changeStyle) & ! methods::is(changeStyle, "Style")){
    cli::cli_abort("`changeStyle` must be NULL or an openxlsx style created with `createStyle()`.")
  }
  if(!is.null(posStyle) & ! methods::is(posStyle, "Style")){
    cli::cli_abort("`posStyle` must be NULL or an openxlsx style created with `createStyle()`.")
  }
  if(!is.null(negStyle) & ! methods::is(negStyle, "Style")){
    cli::cli_abort("`negStyle` must be NULL or an openxlsx style created with `createStyle()`.")
  }
  if(!is.null(df.invert) & !all(names(df.invert)==c("row", "col"))){
    cli::cli_abort("If provided, `df.invert` must be a dataframe with `row` and `col` arguments defining the indices of cells to invert.")
  }



  if(is.null(nofillStyle)){
    nofillStyle <- openxlsx::createStyle(fontColour = "black")
  }
  if(is.null(changeStyle)){
    changeStyle <- openxlsx::createStyle(fontColour = "black", fgFill = "#E1C0FF")
  }
  if(is.null(posStyle)){
    posStyle <- openxlsx::createStyle(fontColour = "black", fgFill = "#FFC7CE")
  }
  if(is.null(negStyle)){
    negStyle <- openxlsx::createStyle(fontColour = "black", fgFill = "#C6EFCE")
  }

  ## empty fills
  openxlsx::addStyle(wb, cur.sheet,
           nofillStyle,
           rows = 1:nrow(sheet.comp$sheet.diff),
           cols = 1:nrow(sheet.comp$sheet.diff),
           gridExpand = TRUE,
           stack = TRUE
  )
  ## If any inversions are identified, apply them to the increase and decrease
  ## But make sure we're not inverting "no change" to "change". Hence the `& mat.changed` bits.
  if(!is.null(rows.invert)){
    sheet.comp$mat.diff.decrease[rows.invert,] = !sheet.comp$mat.diff.decrease[rows.invert,] &
      sheet.comp$mat.changed[rows.invert,]
    sheet.comp$mat.diff.increase[rows.invert,] = !sheet.comp$mat.diff.increase[rows.invert,] &
      sheet.comp$mat.changed[rows.invert,]
  }
  if(!is.null(cols.invert)){
    sheet.comp$mat.diff.decrease[ , cols.invert] = !sheet.comp$mat.diff.decrease[ , cols.invert] &
      sheet.comp$mat.changed[ , cols.invert]
    sheet.comp$mat.diff.increase[ , cols.invert] = !sheet.comp$mat.diff.increase[ , cols.invert] &
      sheet.comp$mat.changed[ , cols.invert]
  }
  if(!is.null(df.invert)){
    sheet.comp$mat.diff.decrease[df.invert$row , df.invert$col] =
      !sheet.comp$mat.diff.decrease[df.invert$row , df.invert$col] &
      sheet.comp$mat.changed[df.invert$row , df.invert$col]
    sheet.comp$mat.diff.increase[df.invert$row , df.invert$col] =
      !sheet.comp$mat.diff.increase[df.invert$row , df.invert$col]&
      sheet.comp$mat.changed[df.invert$row , df.invert$col]
  }

  ## color text changes
  openxlsx::addStyle(wb, cur.sheet,
           style = changeStyle,
           rows = which(sheet.comp$mat.diff.text, arr.ind = TRUE)[,"row"],
           cols = which(sheet.comp$mat.diff.text, arr.ind = TRUE)[,"col"], stack = TRUE)
  ## color numeric declines
  openxlsx::addStyle(wb, cur.sheet,
           style = negStyle,
           rows = which(sheet.comp$mat.diff.decrease, arr.ind = TRUE)[,"row"],
           cols = which(sheet.comp$mat.diff.decrease, arr.ind = TRUE)[,"col"], stack = TRUE)
  openxlsx::addStyle(wb, cur.sheet,
           style = posStyle,
           rows = which(sheet.comp$mat.diff.increase, arr.ind = TRUE)[,"row"],
           cols = which(sheet.comp$mat.diff.increase, arr.ind = TRUE)[,"col"], stack = TRUE)

  return(wb)
}
